### ISSUE TITLE
UI Update for Phone System

### ISSUE THREAD

**Issue by pablo014** [CrisisCleanup/crisiscleanup-3-web#1448]
## Description

Dynamic Phone Component sizing
sm - dialer and statistics
md - text
lg - the rest

fix the new case button

## Tasks

- [x] Add small medium large sizing and apply
- [x] textarea for messaging
- [x] fix new case button
