### ISSUE TITLE
Fix Location Input Process

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#1450]
## Tasks
- [x] Null Error Handling: if field is null:
  1. Scroll up to the field.
  2. Highlight the field red.
  3. Toasted Error
- [x] Ensure that the following fields are required, and apply Null Error Handling:
  - [x] Name
  - [x] Phone1
  - [x] Address
  - [x] [City] (When "Select on Map or "Address Problem" is selected)
  - [x] [County] (When "Select on Map or "Address Problem" is selected)
  - [x] [State] (When "Select on Map or "Address Problem" is selected)
  - [x] [Postal Code] (When "Select on Map or "Address Problem" is selected)
  - [x] At least one Work Type must be selected. Highlight the "Work" section red if possible.
- [x] If the address field is non-null, BUT has not been geocoded (i.e. no latitude or longitude have been created and the blue pin does not appear on the map), then highlight location field red and add an error alert next to the location field: `caseForm.no_lat_lon_error`
- [x] If a user clicks "Select on Map," then:
  - [x] Expose the City, County, State, and Postal Code fields
  - [x] Automatically make the County field editable (it is read-only by default)
  - [x] Turn off geocoding.
  - [x] Apply Null Error Handling on the Address, City, County, State, and Postal Code fields.
  - [x] Make the "Select on Map" a toggled button that turns yellow
- [x] If a user clicks "Select on Map" again, then toggle:
  - [x] Leave the blue pin on the map.
  - [x] Turn on the geocoder, and allow it to override the blue pin selection
  - [x] Re-hide City, County State, and Postal Code fields
  - [x] Make the "Select on Map" a toggled button that turns gray or white again.
- [x] Add a Help button component to "Location:" Use `caseForm.location_instructions`
- [x] Add a new checkbox, "Address Problem" (`caseForm.address_problems`) above "Flag as High Priority." Toggling this checkbox on will:
  - [x] Add or remove a "Wrong Location" flag to the case.
  - [x] Engage or disengage the "Select on Map" feature, as described above.
- [x] Make sure it works on /phone and /cases.
- [x] Make the "Flag as High Priority" and "Member of My Organization" checkboxes NOT RED. When a user has an error, they will check these boxes, thinking that they are red error messages. Instead, make them the same yellow as "+Add Note".
- [x] Ensure all new strings or localizations are labeled with `~~`.
- [x] If the "Full Address" line is non-null AND has not been geocoded, AND a user saves, then activate "Select on Map." However, if "Full Address" line is NULL, then do NOT activate "Select on Map."
  
**REMEMBER: The over-all goal of this issue is to make it easy for someone in the back woods of Kentucky to add an address to the system that Google does not recognize.**

**Comment by aarontitus** [comment]
Bug:
1. Click "Select on Map."
2. Complete the address fields.
3. Complete other required fields.
4. Save.
Error: Cannot find location, even though there is a pin on the map. 
![image](https://user-images.githubusercontent.com/4184619/186937202-95110049-bbd9-4387-9f49-3a830b6d92f8.png)
