### ISSUE TITLE
New Claimed Closed Report Punchlist

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#1458]
**Page Title**
- [ ] Make the Page Title the Name of the report, rather than just "Report"
- [ ] Include the name of the report on the printed version
- [ ] Add, "Report paid for by a grant from Crowdsource Rescue, through June 1, 2023." (`reports.paid_for_statement`)
![image](https://user-images.githubusercontent.com/4184619/185643057-58ee0572-d9d6-4108-96a4-26a9b5433de6.png)

**Filters**
- [ ] Make sure that "Filters" is localized.
- [ ] Limit the contents of all dropdowns to only valid options (i.e. organizations that have been approved for the incident, and not invalidated; work types associated with the incident; locations that intersect with the incident locations).
- [ ] Make all dropdowns multi-select. (i.e. select multiple organizations, multiple work types, multiple locations)
- [ ] By default, an empty filter should read "All" (i.e. All organizations, All work types, All locations)
- [ ] Date Range Picker: By default, start with the first day of the disaster, and end with today.
- [ ] Use something like https://litepie.com/ as the date picker. And if we do, please buy the guy a coffee or two, and add it to the invoice :-).

**Velocity**
Add a new Velocity section, based on the graphic below, except that instead of "Weeks to Completion," it will be labeled "Velocity." For now, this report will be based on `r.pp_es_daily_points`, or the Pew-Pew velocity, and will not have an ego-centric view.
- [ ] Add a large, standard label/title to the chart that I can localize.
- [ ] Line graph from 0-100%
- [ ] Make it interactive: hovering will show the data point.
- [ ] Round to .1% e.g. "70.3%" or "0.1%"
- [ ] Add to widget in small text: "Report paid for by a grant from Crowdsource Rescue, through June 1, 2023." (`reports.paid_for_statement`)
![graph](https://user-images.githubusercontent.com/4184619/185706819-d695cce4-e101-416b-82be-92e7d8670085.jpg)

**Pie Charts**
- [ ] Add a large, standard label/ title to the chart that I can localize.
- [ ] 1. Make interactive: On hover, highlight the pie chart and display a tooltip with the pie slice percentage, count and value
- [ ] 2. Add "In Progress" (note: I've added this to the `primary_status` column).
- [ ] 2/6. Make sure that the "Open" value is not actually the total. If it is, make sure to subtract "Closed" and "In Progress" from the total to get the "Open" count.
- [ ] 2. Change colors: "Open" should be Red (#C10100, or our standard red). Closed should be green (#70AD46 or our standard green) In Progress should be orange (#F69721).
- [ ] 2. Label "Open", "Closed", and "In Progress" with percentages on the pie chart.
- [ ] 3. Change download to button (`actions.download`)
- [ ] 4. Translate "Add to Dashboard" (`reports.add_to_dashboard`)
- [ ] 4. Make "Add to Dashboard" an on-off switch.
- [ ] 5. Wrap pie charts to be multiple rows if necessary.
- [ ] 6. For each pie slice, add the label, count, and value, e.g. "Closed (43, $6,275,270)"
- [ ] 6. Localize dollar values as "$0,000"
In general, draw inspiration from the graphic above.
![image](https://user-images.githubusercontent.com/4184619/185706257-e2c02dde-bd9e-49af-a7b0-6fbaa7596813.png)

**Running Total Count**
- [ ] 1. Add a large, standard label/ title to the chart that I can localize.
- [ ] 2. Add a standard y-axis label to the chart that I can localize.
- [ ] 3. If possible, slant the dates at ~45 degree angle, or other angle that looks good
- [ ] 4. Make interactive: On hover, display a tooltip with the date and value
- [ ] 4. Change line colors: "Total Created Cases" should be Red (#7F060F, or something slightly darker than our standard red). "Total Claimed" (In Progress) should be orange (#C37506 or something slightly darker than our our standard orange). "Total Closed" should be green (#3F6822 or something slightly darker than our our standard green). Note: The lines are slightly darker than their areas.
- [ ] 4. Double or triple the line thickness.
- [ ] 5. Fill in the area below each line, with Total Created cases in back, Total Claimed in the middle, and Total Closed in the front. "Total Created Cases" should be Red (#C10100, or our standard red). "Total Claimed" (In Progress) should be orange (#F69721). "Total Closed" should be green (#70AD46 or our standard green).

![image](https://user-images.githubusercontent.com/4184619/185711942-b0749676-78ab-4159-bc86-53dce0289bd9.png)

**Running Total Value**
Add a new chart based on the same data as the Running Total Count, except for value instead.
- [ ] Follow instructions for Running Total Count Chart.

**Daily Total Count**
- [ ] 1. Add a large, standard label/ title to the chart that I can localize.
- [ ] 2. Add a standard y-axis label to the chart that I can localize.
- [ ] 3. If possible, slant the dates at ~45 degree angle, or other angle that looks good
- [ ] 4. Make interactive: On hover, display a tooltip with the date and value
- [ ] 4. Change line colors: "Created Cases" should be Red (#C10100, or our standard red). "Claimed" (In Progress) should be orange (#F69721). "Closed" should be green (#70AD46 or our our standard green).
- [ ] 5. Add a gap of ~30% the width of a bar between each day.
- [ ] If this looks bad, just do a stacked bar chart, with red on the bottom, orange in the middle, and green on top.

![image](https://user-images.githubusercontent.com/4184619/185713341-3256433d-9b9a-4aa5-bdb9-ab7a67ec8947.png)
