### ISSUE TITLE
Allow User to Manually Push Text Messages to Survivors

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#1483]
## Description
The text message feature has become very popular, and some survivors become very anxious when they do not instantly receive a text. Phone volunteers also become anxious.

## Solution
Give volunteers the ability to manually send a text message to survivors. However, they should not be able to see the contents of the text, because it contains a private link only for the survivor.
Per @tabiodun, to send a notification, the following must be true:
```
* incident.auto_contact needs to be ON
* worksite.auto_contact_frequency_t should not be AutoContactFrequency.NEVER.value:
* incident start should be in the last 60 days
* worksite should have at least 1 valid email or phone number
* at least 1 open work type
```

## Tasks
- [x] Add a font-awesome "comment-lines" icon: `<font-awesome-icon icon="fas fa-comment-lines" />`, `alt = "caseForm.sms"` (See image below)
- [x] When the user clicks the Send Text Message, open an alert (modal or toasted, whichever is easier), with the message, `caseForm.sms_sent`.
- [ ] If any of the requirements above are `false` then hide the SMS button *on the EDIT form* to avoid user confusion.
- [ ] Exception: Make this feature available *on the New Case form* _every time_, and send an SMS upon demand as long as there is a valid email or phone number, even if one or more of the other requirements are false.

![image](https://user-images.githubusercontent.com/4184619/190682692-5d130dad-78ba-4d6e-990c-3f4c85c31b7f.png)

**Comment by aarontitus** [comment]
Could not confirm whether this feature works because the message does not appear in `message_messages`.

**Comment by aarontitus** [comment]
Saving a new case produces a Sentry error: `send_message() missing 1 required positional argument: 'phone_number_override'
`

**Comment by aarontitus** [comment]
Completed.
