### ISSUE TITLE
Recalculate map to account for cases moved away

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#1540]
## Description
The new local cache and database is MUCH faster for /work. However, we are having problems with the local cache getting out of sync with production. See screenshot of Hurricane Fiona below.

## Screenshots
![image](https://user-images.githubusercontent.com/4184619/205091922-0bcdbe79-a23f-4a38-8896-2468a7caac52.png)

## Tasks
- [ ] Create an endpoint that returns a list of current worksite_ids. Compare local cache's list of worksite_ids.
- [ ] If the authoritative list contains worksite_ids that do not exist locally, update those worksites.
- [ ] If the local cache contains worksite_ids that are not in the authoritative list, remove them from the cache.

**Comment by aarontitus** [comment]
Solved.
