### ISSUE TITLE
Design: Activate Special Modules/User Edit Nav Bar 

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#18]
**Problem**
Different users will have access to different modules of the system. For example, the Phone module is hidden by default, to simplify the UI. Users should be able to add it very easily.

**Solution**
Add a "+" at the bottom of the nav bar, where users can add additional modules to the nav bar, such as "Phone." Or in the future, "Donations."

Create an easy way for users to activate any/all of the following modules:
- [ ] Helpdesk Support Agent Module (See Issue CrisisCleanup/old-crisiscleanup-3-web#57 )
- [ ] Advanced Mapping Module (See Issue CrisisCleanup/old-crisiscleanup-3-web#61 )
- [ ] Phone Agent Module (See Issue CrisisCleanup/crisiscleanup-3-web#8 )
- [ ] Translation Module (See Issue CrisisCleanup/old-crisiscleanup-3-web#39 )
- [ ] Any other module created in the future

Some modules will automatically appear depending on the user's role. For example:
- [ ] Affiliate Organizations/ Organization Settings Modules: Appears if user is a Primary Contact (See Issues CrisisCleanup/old-crisiscleanup-3-web#63, CrisisCleanup/crisiscleanup-3-web#12 )
- [ ] Portal Admin Module: Appears only if the user is a Portal Admin (See Issue CrisisCleanup/crisiscleanup-3-web#17 )
- [ ] Also, some modules will automatically activate if a user chooses a specific role (e.g. "Support Agent", Issue CrisisCleanup/crisiscleanup-3-web#16 )

Other Instructions:
- [ ] If a module requires a higher-level role, then the user is directed to Switch Roles, which may require approval from someone else in the organization.

Design for the following Formats:
- [ ] Desktop
- [ ] Tablet
- [ ] Smartphone
- [ ] App
Final Output
- [ ] Wireframe or PSD

**Comment by aarontitus** [comment]
Where can a user find a place to turn on these modules?

**Comment by OlhaUzkykova** [comment]
https://invis.io/WSWBJ383VKC#/378961681_Settings_Menu
