### ISSUE TITLE
Design: Field Work View

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#23]
The field worker's view should be focused on reporting completion and gathering case information (particularly for the app). It should include:
- [x] * Easily find nearby cases based upon location and filters identified in CrisisCleanup/old-crisiscleanup-3-web#12 and CrisisCleanup/old-crisiscleanup-3-web#48 
- [x] Easily claim cases and assign/unassign to team
- [x] * Mark when each work type is completed
- [x] Update the over-all status of the work order
- [x] Log in/log out
- [x] * Check in/check out (e.g. start a passive timer that tracks volunteer time for easy reporting)
- [x] Easily form or join a team
- [x] Declare assets in user's possession (e.g. chainsaws, heavy equipment, van, food, water)
- [x] Capture the names of other workers on a team who are not signed in.
- [x] * Take photographs of home, before and after
- [x] * Video of after/feel-good
- [x] Get homeowner's email address
- [x] * Get homeowner's signature for liability release
- [x] Share photographs and messages on Social Media
- [ ] Record a brief video/oral summary of the day's activities
- [x] Mark a location as in the wrong place on the map (See Issue CrisisCleanup/crisiscleanup-3-web#21)
- [x] Link to Badge (See Issue CrisisCleanup/crisiscleanup-3-web#20).

Design for the following Formats:
- [ ] Desktop
- [ ] Tablet
- [ ] Smartphone
- [ ] App
Final Output
- [ ] Wireframe or PSD
