### ISSUE TITLE
Design: View/ Enter Cases

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#33]
- [x] Map View
- [x] Table View (see Issue CrisisCleanup/crisiscleanup-3-web#30 )
- [x] Filter by:
  - [x] Social Vulnerability Index (SVI). One slider for over-all SVI, and multiple sub-sliders for various SVI data subsets.
  - [x] Status
  - [x] Claimed by My Organization
  - [x] Claimed by My Crew/Team
  - [x] Unclaimed
  - [x] Available work types
  - [x] Each attribute available in the data set
  - [x] County
  - [x] Zip code
  - [x] Custom SHP/KML file
  - [x] Freshness of Data
- [x] Layers
  - [x] SVI
  - [x] Heatmap of PDA/ all data
  - [x] County
  - [x] Zip Code
  - [x] Custom SHP/KML files
  - [x] Current location of my organization volunteers
  - [x] Current location of my crew/team
  - [x] Current location of assets
- [x] Enter Cases
- [x] Claim/Unclaim cases
- [x] Print
- [ ] Email/Send Case
- [ ] Request Case from another Organization
- [ ] Assign case to crew
- [x] SMS/TXT Case data
- [x] View on map
- [x] Case History
- [x] Interactions (See Issue CrisisCleanup/old-crisiscleanup-3-web#35 )
- [x] Download CSV
- [x] Flag the case as in the wrong location (See Issue CrisisCleanup/crisiscleanup-3-web#21 )
- [x] Easily move the map pin to a different location.

Design for the following Formats:
- [x] Desktop
- [ ] Tablet
- [ ] Smartphone
- [ ] App
Final Output
- [ ] Wireframe or PSD
