### ISSUE TITLE
Connect Call Pop Up

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#340]
**Describe the problem**
When a call is about to happen, we show this pop up that gives some context to the agent as to what is about to happen.

**Describe the solution**
Show pop up depending on the type of call it is (inbound, call back, call down)

**Additional context and instructions**

- [x] create pop up screen as defined below
- [ ] make title dynamic based on the type of call it is (inbound, call back, call down)
- [x] highlight the title word "incoming" in this color
![image](https://user-images.githubusercontent.com/699333/76675967-15472680-658d-11ea-862a-f9961531fb40.png)

- [ ] highlight the title words "returning" and "following up" in this color
![image](https://user-images.githubusercontent.com/699333/76675954-ec269600-658c-11ea-9512-f0b58aa08f78.png)

- [ ] show any phone information we have based on image
- [x] show sample script based on the type of call it is (inbound, call back, call down). **NOTE:  This sample script section will also be re-used on a stand alone card here #341 .... so make this a re-usable component.**. 
- [ ] show the type of buttons based on call type (inbound, call back, call down)
- [ ] Decline and Cancel buttons both will close the window and put the agent in "offline" state
- [ ] Accept will load up the #294 screen
- [ ] Start will load up the #294 screen (and as a side note for another case, start the call flow

![image](https://user-images.githubusercontent.com/699333/76675806-81288f80-658b-11ea-934f-a3edaeb5d192.png)
