### ISSUE TITLE
3 kinds of helper scripts

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#341]
- [ ] depending on the type of call (inbound, call back, call down) display the appropriate script as defined in case #340 
- [x] put it on top of the screen #294 
- [x] add a checkbox on the bottom that says "do not show this again"
- [ ] if you check the box "do not show this again" then display a popup message that says "You can always turn this back on from settings"
- [x] when you dismiss the "you can always.... " pop up, also hide this sample script card and slide up the rest of the #294 screen.  
- [x] BONUS PRIZE only if it is easy:  animate the pop and slide up process.
- [ ] Add a place in the user settings to "show sample scripts in the phone section"

![image](https://user-images.githubusercontent.com/699333/76676198-25f89c00-658f-11ea-9ab6-b127f4685cf3.png)

![image](https://user-images.githubusercontent.com/699333/76676428-7244db80-6591-11ea-8a9a-25fc282ec2a0.png)

See image below for the scripts we should show for each type of call

- [x ] **show script for inbound call**
you have done this.. 

- [ ] **show script for callback**

"My name is _______ from the Crisis Cleanup Hotline. Someone from this number called to ask for help cleaning up after a recent disaster. I am returning your call."

- [ ] **Show script for call down**

"My name is _______ from the Crisis Cleanup hotline. We noticed that you asked for help a while ago. I was just following up to make sure you still needed help.  Do you still need help? "

If Yes:  “I want to let you know that you are still on the list, it may take a very long time to receive help, but you are definitely on the list.”

If No:  “Thank you so much for the update and I will go ahead and update the map”.

![](https://user-images.githubusercontent.com/699333/76675806-81288f80-658b-11ea-934f-a3edaeb5d192.png)

**Comment by arroyoDev** [comment]
Almost done. 

- [ ] change background color of pop up to 
![image](https://user-images.githubusercontent.com/699333/78569678-92ab3300-77e9-11ea-9472-ac2e00da603a.png)

On the scripts tab that is still there, go ahead and make the page live 
- [ ] add a checkbox to "Show scripts on top of page for live calls"
- [ ] add the following text to the page for sample scripts. 

![image](https://user-images.githubusercontent.com/699333/78569818-c4bc9500-77e9-11ea-9ab5-9ce39faa8b44.png)

- [ ] When you initially click the "Do not show this again" message, show a quick message that says "ok, turning this off, but if you want it back, go to the scripts tab to turn it back on".

**Comment by arroyoDev** [comment]
Finished and move the rest to a new issue.
