### ISSUE TITLE
Training Flow (Backend)

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-3-web#407]
@JamesRArroyo great work on getting the bulk of this worked out

@BradenM  all that is left is to wire this up so that when a user first comes to the phone page we have a database setting of "phone training complete". It is assumed that nobody has been trained.  The "Start Taking Calls" button would actually say "Start Training" if the flag is null or false.  Launching the rest works. with the Pr jimmy just did.  
When training is done, set the flag so we don't prompt them again (until a day when we want them to do another round of training if that happens at a future point we would just re-set their flag and they go again).

In order for a volunteer to be able to work the phones, they need to do some quick training.  This flow is design to help make that happen. 

- [ ] **Braden:**  By default, all volunteers should have a flag "phone training complete" which by default is null
- [ ]  if the phoneTrainingComplete flag is not true, then the "Start Taking Calls" button should say "Start Training" instead.  
![image](https://user-images.githubusercontent.com/699333/77392589-4ed81880-6d69-11ea-9e6d-4b9b481a2a8a.png)
- [ ] "Start Training" Should launch the Training Launcher Page #402 
- [x] Each module on the training launcher page should link to a Training Details page #404 
- [x] Each Training Details page should have 3 simple questions that you have to get correct in order to enable the "Complete quiz" button.
- [x] If you "Complete the Quiz" then the window closes and you update the training item to "Completed"  https://projects.invisionapp.com/d/main#/console/14746784/338201796/preview
- [x] for now totally skip the custom instructions thing... no time
- [x] once all training modules are "completed" (we will only have 2 for a while), then enable the "Next button". https://projects.invisionapp.com/d/main#/console/14746784/338201796/preview
- [x] The Next button will take us to the "Training Finish" page #405 which will allow the user to review and edit their phone number and languages.   
- [ ] **Braden:** Hitting "Confirm" will set the "phoneTrainingComplete" flag to true and the "Avialibilty" Button will now do what it is supposed to do.
