### ISSUE TITLE
Event Builder UI Updates

### ISSUE THREAD

**Issue by BradenM** [CrisisCleanup/crisiscleanup-3-web#889]
**Todo**

- [x] Distinguish FormSelect focused fonts
- [x] Display Raw Key next to localized dropdown choices
- [x] Setup elasticsearch staging/prod
- [x] Implement merge constraints (Must have patient/recipient, must be same type)
- [x] Add "None" option to User Badge dropdown, making it null-able only explicitly
- [x] Determine why some event component objects are being shy in the dropdown options
- [x] Move Join constraint violation field errors to key field
- [x] Fix issues where it appears the form does not fully clear
- [x] Add explicit errors on missing action/actor key

**Comment by BradenM** [comment]
Closed by #890 and API#352
