### ISSUE TITLE
On Going Public

### ISSUE THREAD

**Issue by BradenM** [CrisisCleanup/crisiscleanup-3-web#96]
**Todo**

- [ ] **Possibly** Setup a [Vault](https://www.vaultproject.io/) server for sharing any/all sensitive information between team members.

- [ ] **Possibly** remove need for .env files by authenticating and retrieving any information via the Rest API Vault provides. Will have to read more into it.

- [ ] **Possibly** just write a small script for automating .env/other file setups via fetching/syncing with vault (something like `cc3 sync/pull/push web/api/v2`?)

- [x] Use the black magic of [BFG](https://rtyley.github.io/bfg-repo-cleaner/) to erase any sensitive information pushed from existence.

- [x] Create sample .env files in their place

- [x] Update any public documentation.

- [x] Remove live credentials from tests

- [x] Remove any Google Maps keys
- [ ] Add/fix contributing guidelines, code of conduct, licensing, notices, etc.

- [ ] Set Github permissions for merging/pull requests.

Feel free to add something if needed.

**Comment by BradenM** [comment]
:tada: Now public :tada:
