### ISSUE TITLE
CI Workflows and Integrations

### ISSUE THREAD

**Issue by BradenM** [CrisisCleanup/crisiscleanup-3-web#98]
**Overview**

Use git workflows/actions for project CI/CD, project automation (PR formatting, PR checks, etc), git integrations (coveralls, actions, etc).

**Todo**

Primary Workflow:

- [x] Run testing suite
- [x] Build site
- [x] Linting checks
- [x] Deploy staging / live environments

Integrations:

*Note: most integrations are free for public open source, so #96 will likely need to be addressed prior to this*

- [ ] Coverage Reporting ([coveralls.io](https://coveralls.io/), possibly.)
- [ ] PR Formatting / Auto label - *not priority*

@tabiodun, would like to hear what you think about this as I know some of this is currently implemented in the Jenkins server, but it is apparently not up to date. See slack discussion in #core.
