### ISSUE TITLE
Phone UX Improvements, Skipping calls through UI, Panic Button, Bug Fixes

### ISSUE THREAD

**Issue by BradenM** [CrisisCleanup/crisiscleanup-3-web#986]
## UX Improvements

**Currently many phone agent's are being led to believe they are in an offline state when they aren't.**

To improve and resolve this issue:
- [x] Add a global phone indicator next to the user's profile image that will indicate the agent's current status on every page.
- [x] Instead of looking through "idle" agent's and essentially giving it our best guess as to whether the agent's intention is to be online or offline, simply allow idling as long as the client is still connected. Once the client is disconnected, immediately set the agent offline. **Closed by**: https://github.com/CrisisCleanup/crisiscleanup-3-awsconnect/commit/de8cf81a9645fb3f134d107cbc0748a4a0dc2fe5

**Agent's feel as if they are being locked into a call and are unable to reject/deny and/or are doing a disservice to a survivor.**

- [x] Add a button to the incoming call popup labeled "Skip Call." When clicked, as a minimum, display instructions explaining that the agent will shortly receive a call prompting them whether or not they wish to accept the call. Instruct them to select 0 to deny or to simply deny the call. Also explain that no survivor is an anyway impacted by the agent's denial, and that they will not be called (in the case of an outbound) or that they will continue on to the next agent transparently (in the case of an inbound.) **Closed By:** #994 -- Skipping call also end the call automatically.

- [x] When skipping call, also stop more calls. See #995 **Closed by API#399 & #1005**

- [x] On manual outbound, if user does not press 1, the user should go offline, but does not. Or user should go back to whatever state they were in prior to making a manual outbound call. **Closed by #1005**

- [x] ~~Add a new "hang-up" button to the left of the primary start/stop taking calls button in the agent card. This button will act as a "panic button" and will always provide the agent with a method of ending/rejecting the current contact.~~ Replaced by skip call button.

## Bug Fixes

**Inbound Call Flow**

- [x] Rejecting an inbound call does not currently destroy the agent client's local contact instance. This prevents the agent from actually going offline and prevent the release of the currently locked contact ID. If the agent forces themselves offline (via a refresh or similar), the contact id will remain locked and therefore not rollover to a new agent -- eventually forcing the user into a callback. **Closed by**: API#396

**General Metrics**

- [x] "Currently on Hold" counter is no longer incrementing. This is due to the contact action updates as an indirect result of the inbound event changes. **Closed by**: API#396

## Contact Flow

**Queue Music**

- [x] The music played while a contact is in the queue is still cutting up and restarting every 25 seconds. I tried taking the 6 minute clip of music, splicing it into 16 different prompts, each 25 seconds long, and adding all 16 to the prompt loop list. Did not seem to work. Will need some investigating. **Moved to:** #1047

**Comment by BradenM** [comment]
Closed wrong issue, meant to close #995
